name: Generate RSS XML

on:
  schedule:
    - cron: '0 * * * *' # Menjalankan setiap jam
  workflow_dispatch: # Bisa dijalankan manual

jobs:
  generate-rss:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: pip install feedparser

      - name: Fetch Latest RSS Items
        run: python generate_rss.py

      - name: Commit and Push Changes
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add rss.xml
          git commit -m "Update RSS feed" || echo "No changes to commit"
          git push https://$GH_PAT@github.com/harboot/rss.git main
